{
  "Version": "2.0",
  "FiscalInfo": null,
  "QuebecCheckDate": null,
  "FiscalLotteryCode": null,
  "PurchaseCode": null,
  "AdditionalInfo": null,
  "ColombiaCustomInfo": null,
  "FiscalText": null,
  "FiscalTaxSummary": null,
  "ORNumber": null,
  "ARNumber": null,
  "TaxInvoiceNumber": null,
  "CheckSearchType": "2",
  "IrnNumber": null,
  "GuestAccountNumber": null,
  "IndiaGuestInfo": null,
  "PMSBestDiscAmt": "0",
  "IsAutoPackaged": false,
  "IsLiveEntertainmentTax": false,
  "EngageAccuralTransactionId": "0",
  "AllowMultiLevelDiscount": false,
  "AllowDiscount": false,
  "OrderNumber": "15000018",
  "IsDiscountTO345Enabled": true,
  "nonDiscountableSVCSaleBasisAmt": "0",
  "CloseTimeTicks": "17476341255950932",
  "IsLimitedReopenFlag": false,
  "IsIRSEnabled": true,
  "TipValue": "0",
  "IsoCurrencyCode": "KRW",
  "OpenTimeTicks": "17476338025502304",
  "IsBrunswickInterfaceEnabled": false,
  "InclusiveServiceCharge": "0",
  "TeamName": "",
  "RestrictedItemTaxAmount": "0",
  "IsScheduledCheckFinalPayment": false,
  "RestrictedAuthTenderAmount": "0",
  "CheckTotalWithoutRound": "62499",
  "IsReopen": false,
  "TaxIncItemsGroupedSVCValue": "0",
  "TerminalOptionGroup": {
    "Id": "18",
    "SortOrder": true,
    "IsSortByCheckTotalAmt": false,
    "IsDisplayCheckTotalAmt": false,
    "IsDisplayServerName": false,
    "Timeout": "0",
    "AllowAutoSignOff": false
  },
  "SplitAllItemsCount": "0",
  "CurrentTenderId": "0",
  "AuthorizedAmount": "0",
  "KitchenSchedule": {
    "KVJobId": "0",
    "KPJobId": "0",
    "ScheduledTime": "0"
  },
  "AutoApplyCheckLevelDiscountToAllItems": false,
  "EvenSplitCount": "0",
  "IsClosedRefund": false,
  "IsInclusiveGratuityModeEnabled": true,
  "IsGratTO186Enabled": true,
  "HyattGoldPassFlag": true,
  "IsVATModeEnabled": false,
  "DiscountAmount": "0",
  "CurrentTenderTipAmount": "0",
  "IsSaveAndRecalled": false,
  "Terminal": {
    "OpenedProfitCenterId": "18",
    "OpenedProfitCenterDimId": "0",
    "Id": "150",
    "TenderedTermId": "150",
    "ProfitCenter": "18",
    "TerminalModes": "2",
    "PrintTermId": "0",
    "TerminalDimId": "0",
    "TenderedTerminalDimId": "0",
    "ProfitCenterDimId": "0",
    "MealPeriodDimId": "0"
  },
  "ClosedBy": {
    "Id": "1",
    "EmpShiftId": "0",
    "EmployeeDimId": "0",
    "EmpJobCode": "8",
    "Name": "Supervisor",
    "Percentage": "0"
  },
  "IsTaxRemoved": false,
  "IsMealCheck": false,
  "ReceiptPrintCount": "0",
  "IsDiscountWithoutTO": false,
  "TaxIncItemsGratValue": "0",
  "CheckTypeDimId": "0",
  "RestrictedTenderAmount": "0",
  "IsDiscountTO347Enabled": false,
  "CheckType": "18",
  "TenderAmountAfterTaxRemoval": "0",
  "RestrictedItemAmount": "0",
  "IsTO405Enabled": true,
  "CheckObjectType": "0",
  "IsAlcoholEligible": false,
  "TenderForServiceCharge": "0",
  "IsCheckLabel": false,
  "ServiceChargeValue": "0",
  "MaxDiscountLimitPerCheck": "0",
  "IsTobaccoEligible": false,
  "SplitIdx": "0",
  "CheckTotal": "62499",
  "IsGiftCardUnMask": false,
  "TenderRoundAmount": "0",
  "IsRestrictedTOServiceCharge": false,
  "RecallCount": "0",
  "IsRestrictAlcoholItems": false,
  "Tax": "5682",
  "IsConsumed": false,
  "IsDiscountTO346Enabled": false,
  "RestrictedAmount": "62499",
  "IsCompTenderRemoveTax": false,
  "BarCodeVerificationStatus": "0",
  "DataTagType": "0",
  "SplitSeatId": "0",
  "IsoCountryCode": "KR",
  "CloseTime": "2025-05-19 05:55:25",
  "BalanceAmount": "0",
  "IsDiscountTO1220Enabled": false,
  "Amount": "56817",
  "GratuityValue": "0",
  "InclusiveTax": "0",
  "EvenSplitFinalAmount": "0",
  "CheckClosedSourceType": "1",
  "IsCMPPIIEncrypt": false,
  "RoundAmount": "0",
  "IsCurrentTenderAutoRemoveTax": false,
  "IsGDPR": false,
  "IsRestrictTobaccoItems": false,
  "CurrentCourseId": "1",
  "AllowExclusiveDiscount": false,
  "PreAuthTaxAmount": "0",
  "ChangeAmount": "0",
  "TenderNonAutoDiscAmount": "0",
  "WithheldValue": "0",
  "ServiceChargeState": "0",
  "DiscountOnTaxInclusiveItems": "0",
  "IsSVCTO188Enabled": false,
  "OpenTime": "2025-05-19 05:50:02",
  "SelectionGroupMaxCheckTotalValidationFailed": false,
  "IsCalculateDiscountOnNet": true,
  "IsDiscountTO11Enabled": true,
  "IsDiscountTO348Enabled": false,
  "IsCurrentTnderRestricted": false,
  "IsSplitParentCheck": false,
  "ModifiedVatDifferenceAmt": "0",
  "MealPeriodDimId": "0",
  "IsSaveCasionPlayerDetails": false,
  "GroupedServiceChargeValue": "0",
  "GiftCardBalance": "0",
  "TaxIncItemsSVCValue": "0",
  "MealPeriod": "2",
  "RestrictedTenderedTipAmount": "0",
  "IsCasinoEnabled": false,
  "PriceLevel": "1",
  "UnRestrictedItemAmount": "56817",
  "KSSEventType": "1",
  "DefaultItemKitchenStatus": "0",
  "HasAnyHoldItems": false,
  "SplitAmountMax": "0",
  "IsOfflineCheck": false,
  "SplitAmount": "0",
  "OpenedBy": {
    "Id": "1",
    "EmpShiftId": "0",
    "EmployeeDimId": "0",
    "EmpJobCode": "8",
    "Name": "Supervisor",
    "Percentage": "0"
  },
  "OpenTimeInMilliSeconds": "1747633802550",
  "ThresholdTaxId": "0",
  "IsCompleteTender": false,
  "BalanceAmountWithoutRounding": "0",
  "DiscountMultiModeFlag": false,
  "TO1016MutlipyFactor": "1",
  "IsTaxIncItemsTO13Enabled": false,
  "CheckPassCount": "0",
  "IsTO1016Enabled": true,
  "CloseTimeInMilliSeconds": "1747634125595",
  "nonDiscountableGratSaleBasisAmt": "0",
  "GratuityState": "0",
  "InclusiveGratuity": "0",
  "ApplicableRestrictedTenderAmount": "0",
  "IsModifiedVatToServiceCharge": false,
  "TenderDiscountAmount": "0",
  "GroupedGratuityValue": "0",
  "CheckStatus": "9",
  "CurrentTenderAmount": "0",
  "TeamId": "0",
  "TotalMealCount": "5",
  "IsFoodServiceLoyaltyEnabled": false,
  "IsSplitted": false,
  "IsRestrictedTOGratAndTip": false,
  "ThresholdAmount": "0",
  "TableNumber": "D20",
  "GrossCheckTotal": "62499",
  "CreditTender": "0",
  "IsOfflineClosedRefundCheck": false,
  "IsEntDecimalFlag": false,
  "IsTaxExcItemsTO70Enabled": false,
  "TenderForGratuity": "0",
  "SplitAmountMaxThreshold": "0",
  "TaxIncItemsGroupedGratValue": "0",
  "CheckOpenSourceType": "1",
  "RestrictedCheckItemAmount": "0",
  "IsEncrypted": false,
  "UniqueKeyNumber": "0",
  "RoundingConfiguration": {
    "RoundType": "1",
    "RoundBasis": "1"
  },
  "ISTO185Enabled": false,
  "VoidInfo": {
    "DimId": "0",
    "TimeTicks": "0"
  },
  "UnRestrictedItemTaxAmount": "5681.7",
  "IsAgeManuallyVerified": false,
  "TipValue2": "0",
  "IsRefund": false,
  "BreakageAmount": "0",
  "IsTaxTO185Enabled": false,
  "CheckHandle": {
    "CheckNumber": "15000018",
    "OrderCodeNumber": "18",
    "Guid": "3440fdfb-7e00-49da-878e-4a93fa106730",
    "LockedByTermId": "0",
    "LongCheckNumber": "2025139000015000018"
  },
  "PMSAccountDiscountAmount": "0",
  "GrossAmount": "56817",
  "EvenSplitAmount": "0",
  "Vipseat": [
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false
  ],
  "DataString": [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    ""
  ],
  "DataInteger": [
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0"
  ],
  "SeatTotal": [
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0"
  ],
  "CheckCoverCount": "1",
  "RecalledCheckLastQSRIndex": "0",
  "CheckKitchenItemIndex": "5",
  "NoOfDecimals": "0",
  "OpenGratuityPercent": "0",
  "OpenServiceChargePercent": "0",
  "OpenGratuityAmount": "0",
  "OpenServiceChargeAmount": "0",
  "Context": {
    "CustomerId": "0",
    "EnterpriseId": "1",
    "DivisionId": "1",
    "StoreId": "1",
    "TerminalId": "150",
    "PropertyDTTM": null,
    "CurrencyCulture": "ko-KR",
    "TimeZone": "Korea Standard Time",
    "ProfileId": "27"
  },
  "CheckItems": [
    {
      "IsPriceOverride": false,
      "IsRestricted": false,
      "FixedExclusiveTaxAmount": "0",
      "KitchenItemIndex": "1",
      "DiscountAmount": "0",
      "OrderItemType": "0",
      "MaxItemPrice": "0",
      "OpenItemInitialPrice": "0",
      "IsVoided": false,
      "IsSoldByWeight": false,
      "ItemTaxAmount": "0",
      "IsTaxRemoved": false,
      "IsConsumed": true,
      "CourseId": "1",
      "Cost": "0",
      "SeatNumber": "1",
      "IsMaxItemPrice": false,
      "InclusiveGratuityAmount": "0",
      "QuantityFraction": "0",
      "IsOpenPrice": false,
      "Name": "Korean",
      "IsOpenNamePrompt": false,
      "RestrictedItemGrossCost": "0",
      "SplitAllItemsMethod": "0",
      "IsReturnItem": false,
      "ReplacedItemId": "0",
      "OverrideApprovedBy": {
        "EmpShiftId": "0",
        "EmployeeDimId": "0",
        "Percentage": "0"
      },
      "IsVoidable": true,
      "ItemCheckNumber": "0",
      "IsBarGunItem": false,
      "ObjectIndex": "1",
      "RestrictedItemCost": "0",
      "FixedInclusiveTaxAmount": "0",
      "PackageId": "0",
      "RevenueCost": "0",
      "ItemCoverCount": "1",
      "IsSaved": false,
      "Quantity": "1",
      "DisplayCost": "0",
      "GrossCost": "0",
      "GetModifierCost": "0",
      "TotalTaxAmount": "0",
      "Index": "1",
      "NonTaxableAmount": "0",
      "InclusiveServiceChargeAmount": "0",
      "IsManualPackage": false,
      "UnRestrictedItemCost": "0",
      "ReplacedItemDimId": "0",
      "InclusiveTaxAmount": "0",
      "AllowPriceOveride": true,
      "OrderItems": [
        {
          "SelectionGroupId": "0",
          "CheckTypeDimId": "0",
          "VoidReasonId": "0",
          "ItemQuantity": "0",
          "Cost": "0",
          "MenuItemQuantityCategoryDimID": "0",
          "MaxCalories": "0",
          "ItemCheckNumber": "15000018",
          "PrimaryDiscountId": "0",
          "NonTaxableAmount": "0",
          "ProfitCenter": "18",
          "QuantityCategoryId": "0",
          "InclusiveGratuityAmount": "0",
          "Weight": "0",
          "ChoiceGroupFlag": false,
          "IsInclusiveGratuityModeEnabled": true,
          "UIIndex": "0",
          "ChildItemIndex": "0",
          "DisplayCost": "0",
          "AddedBy": {
            "Id": "1",
            "EmpShiftId": "0",
            "EmployeeDimId": "0",
            "EmpJobCode": "8",
            "Name": "Supervisor",
            "Percentage": "0"
          },
          "IsRestricted": false,
          "IsPrintOnCheck": false,
          "Sequence": "0",
          "FixedExclusiveTax": "0",
          "CheckType": "18",
          "PickupInfo": {
            "IsLaterPickup": false
          },
          "AuxSplitFlag": false,
          "IsQCAddedModifier": false,
          "ModifierDimId": "0",
          "RevenueCost": "0",
          "MealCount": "0",
          "IsAppendModifier": false,
          "DisplayName": "Korean",
          "ModifierIndex": "0",
          "IsManualWeight": false,
          "KpStatus": "1",
          "ScaleFactor": "1",
          "ItemSplitQuantityValue": "0",
          "ModifierCost": "0",
          "Name": "Korean",
          "IsSaved": false,
          "IsAlcoholRestricted": false,
          "IsOpenItem": false,
          "MenuItemDimId": "0",
          "SKUCode": "",
          "NumOfSplits": "0",
          "InclusiveTaxAmount": "0",
          "VoidReasonDimId": "0",
          "IsQCAddedItem": false,
          "OpenItem": {
            "Id": "0",
            "KitchenItemIndex": "0"
          },
          "ProductClassId": "800",
          "IsTaxInclusive": false,
          "CostBeforePackaging": "0",
          "IsDiscountable": true,
          "KitchenVideoCookTime": "0",
          "IsMealItem": false,
          "IUniqueSelGrpId": "0",
          "MaxItemPrice": "0",
          "IsSoldByWeight": false,
          "MealPeriod": "2",
          "IsTobaccoRestricted": false,
          "KitchenItemIndex": "1",
          "ItemVatTax": "0",
          "IsToDisplaySelGrpName": false,
          "TaxGroupId": "1",
          "IsSplitted": false,
          "KitchenVideoDepartmentId": "0",
          "ItemTaxAmount": "0",
          "ModifierProductMixDimId": "0",
          "TaxAmount": "0",
          "Quantity": "1",
          "ModifierProductMixRevenueCost": "0",
          "ReplacedItemDimId": "0",
          "IsStockItem": false,
          "MealPeriodDimId": "0",
          "IsReturnItem": false,
          "KitchenVideoCategoryId": "0",
          "InclusiveServiceChargeAmount": "0",
          "OriginProfitCenterDimId": "0",
          "ModifierProductMixId": "0",
          "ValidateThreshold": false,
          "UnitPrice": "0",
          "RevenueCategory": {
            "InclusiveTaxAmount": "0",
            "SalesAmount": "0",
            "Id": "5",
            "IsRedeemEligible": true,
            "SalesAmountTaxInclusive": "0",
            "RevCatDimId": "0",
            "IsTenderRestricted": false,
            "IsEarnEligible": true,
            "NoTaxNetSales": "0",
            "GroupId": "3",
            "IRSFlag": true,
            "ExclusiveTaxAmount": "0",
            "TaxIclusiveItemDiscountAmount": "0",
            "DiscountAmount": "0"
          },
          "BoxCarCost": "0",
          "Index": "0",
          "MealPeriodReporting": false,
          "IsItemLockout": false,
          "BaseCalories": "0",
          "SeatNumber": "1",
          "TareWeight": "0",
          "QuantityFraction": "0",
          "IsVoided": false,
          "RevenueGroup": "3",
          "ItemCoverCount": "1",
          "IsPackagePmixFlag": false,
          "ProfitCenterDimId": "0",
          "KvStatus": "1",
          "ReplacedItemId": "0",
          "DiscountAmount": "0",
          "AddedTime": "2025-05-19 05:50:04",
          "IsConsumed": true,
          "DisplayRoundId": "0",
          "QCQuantityMultiplier": "1",
          "ConfigItemIndex": "0",
          "ChoiceGroupId": "0",
          "IsGiftItem": false,
          "QCPriceMultiplier": "1",
          "RoundId": "0",
          "IsMaxItemPrice": false,
          "OpenItemInitialPrice": "0",
          "PackagePmixAmount": "0",
          "IsPriceOverriden": false,
          "FixedInclusiveTax": "0",
          "PreviousVoidReasonId": "0",
          "IsModifier": false,
          "ThresholdTaxId": "0",
          "ItemGroupId": "1",
          "CheckViewCost": "0",
          "MenuItemGroupName": "Default Item Group",
          "Id": "100000",
          "Taxes": {
            "ExclusiveCost": "0",
            "InclusiveCost": "0",
            "FixedInclusiveCost": "0",
            "FixedExclusiveCost": "0",
            "RemovedTaxPercent": "0",
            "Count": "2",
            "Details": [
              {
                "UpdatedTaxRate": "0",
                "Id": "1",
                "TaxDimId": "0",
                "IsTaxByPercent": true,
                "TaxValue": "0",
                "IsExclusive": true,
                "IsTaxRemoved": false,
                "CanRemoveAtTerminal": true,
                "CategoryId": "1",
                "IsEarnEligible": false,
                "IsRedeemEligible": true,
                "RoundingConfiguration": {
                  "RoundType": "3",
                  "RoundBasis": "1"
                },
                "InclusiveCost": "0",
                "ExclusiveCost": "0",
                "Amount": "0",
                "TaxCost": "0"
              },
              {
                "UpdatedTaxRate": "0",
                "Id": "2",
                "TaxDimId": "0",
                "IsTaxByPercent": true,
                "TaxValue": "10",
                "IsExclusive": true,
                "IsTaxRemoved": false,
                "CanRemoveAtTerminal": true,
                "CategoryId": "1",
                "IsEarnEligible": false,
                "IsRedeemEligible": true,
                "RoundingConfiguration": {
                  "RoundType": "3",
                  "RoundBasis": "1"
                },
                "InclusiveCost": "0",
                "ExclusiveCost": "0",
                "Amount": "0",
                "TaxCost": "0"
              }
            ]
          }
        }
      ]
    },
    {
      "IsPriceOverride": false,
      "IsRestricted": false,
      "FixedExclusiveTaxAmount": "0",
      "KitchenItemIndex": "2",
      "DiscountAmount": "0",
      "OrderItemType": "0",
      "MaxItemPrice": "0",
      "OpenItemInitialPrice": "6818",
      "IsVoided": false,
      "IsSoldByWeight": false,
      "ItemTaxAmount": "681.8",
      "IsTaxRemoved": false,
      "IsConsumed": true,
      "CourseId": "1",
      "Cost": "6818",
      "SeatNumber": "1",
      "IsMaxItemPrice": false,
      "InclusiveGratuityAmount": "0",
      "QuantityFraction": "0",
      "IsOpenPrice": false,
      "Name": "Mini gouda 20",
      "IsOpenNamePrompt": false,
      "RestrictedItemGrossCost": "0",
      "SplitAllItemsMethod": "0",
      "IsReturnItem": false,
      "ReplacedItemId": "0",
      "OverrideApprovedBy": {
        "EmpShiftId": "0",
        "EmployeeDimId": "0",
        "Percentage": "0"
      },
      "IsVoidable": true,
      "ItemCheckNumber": "0",
      "IsBarGunItem": false,
      "ObjectIndex": "2",
      "RestrictedItemCost": "0",
      "FixedInclusiveTaxAmount": "0",
      "PackageId": "0",
      "RevenueCost": "0",
      "ItemCoverCount": "0",
      "IsSaved": false,
      "Quantity": "1",
      "DisplayCost": "6818",
      "GrossCost": "6818",
      "GetModifierCost": "0",
      "TotalTaxAmount": "681.8",
      "Index": "2",
      "NonTaxableAmount": "0",
      "InclusiveServiceChargeAmount": "0",
      "IsManualPackage": false,
      "UnRestrictedItemCost": "6818",
      "ReplacedItemDimId": "0",
      "InclusiveTaxAmount": "0",
      "AllowPriceOveride": true,
      "OrderItems": [
        {
          "SelectionGroupId": "0",
          "CheckTypeDimId": "0",
          "VoidReasonId": "0",
          "ItemQuantity": "0",
          "Cost": "6818",
          "MenuItemQuantityCategoryDimID": "0",
          "MaxCalories": "0",
          "ItemCheckNumber": "15000018",
          "PrimaryDiscountId": "0",
          "NonTaxableAmount": "0",
          "ProfitCenter": "18",
          "QuantityCategoryId": "0",
          "InclusiveGratuityAmount": "0",
          "Weight": "0",
          "ChoiceGroupFlag": false,
          "IsInclusiveGratuityModeEnabled": true,
          "UIIndex": "0",
          "ChildItemIndex": "0",
          "DisplayCost": "6818",
          "AddedBy": {
            "Id": "1",
            "EmpShiftId": "0",
            "EmployeeDimId": "0",
            "EmpJobCode": "8",
            "Name": "Supervisor",
            "Percentage": "0"
          },
          "IsRestricted": false,
          "IsPrintOnCheck": true,
          "Sequence": "0",
          "FixedExclusiveTax": "0",
          "CheckType": "18",
          "PickupInfo": {
            "IsLaterPickup": false
          },
          "AuxSplitFlag": false,
          "IsQCAddedModifier": false,
          "ModifierDimId": "0",
          "RevenueCost": "0",
          "MealCount": "0",
          "IsAppendModifier": false,
          "DisplayName": "18 Mini gouda 20",
          "ModifierIndex": "0",
          "IsManualWeight": false,
          "KpStatus": "1",
          "ScaleFactor": "1",
          "ItemSplitQuantityValue": "0",
          "ModifierCost": "0",
          "Name": "Mini gouda 20",
          "IsSaved": false,
          "IsAlcoholRestricted": false,
          "IsOpenItem": false,
          "MenuItemDimId": "0",
          "SKUCode": "8809317180106",
          "NumOfSplits": "0",
          "InclusiveTaxAmount": "0",
          "VoidReasonDimId": "0",
          "IsQCAddedItem": false,
          "OpenItem": {
            "Id": "0",
            "KitchenItemIndex": "0"
          },
          "ProductClassId": "4",
          "IsTaxInclusive": false,
          "CostBeforePackaging": "0",
          "IsDiscountable": true,
          "KitchenVideoCookTime": "0",
          "IsMealItem": false,
          "IUniqueSelGrpId": "0",
          "MaxItemPrice": "0",
          "IsSoldByWeight": false,
          "MealPeriod": "2",
          "IsTobaccoRestricted": false,
          "KitchenItemIndex": "2",
          "ItemVatTax": "0",
          "IsToDisplaySelGrpName": false,
          "TaxGroupId": "1",
          "IsSplitted": false,
          "KitchenVideoDepartmentId": "0",
          "ItemTaxAmount": "681.8",
          "ModifierProductMixDimId": "0",
          "TaxAmount": "681.8",
          "Quantity": "1",
          "ModifierProductMixRevenueCost": "0",
          "ReplacedItemDimId": "0",
          "IsStockItem": false,
          "MealPeriodDimId": "0",
          "IsReturnItem": false,
          "KitchenVideoCategoryId": "0",
          "InclusiveServiceChargeAmount": "0",
          "OriginProfitCenterDimId": "0",
          "ModifierProductMixId": "0",
          "ValidateThreshold": false,
          "UnitPrice": "6818",
          "RevenueCategory": {
            "InclusiveTaxAmount": "0",
            "SalesAmount": "0",
            "Id": "1",
            "IsRedeemEligible": true,
            "SalesAmountTaxInclusive": "0",
            "RevCatDimId": "0",
            "IsTenderRestricted": false,
            "IsEarnEligible": true,
            "NoTaxNetSales": "0",
            "GroupId": "2",
            "IRSFlag": true,
            "ExclusiveTaxAmount": "0",
            "TaxIclusiveItemDiscountAmount": "0",
            "DiscountAmount": "0"
          },
          "BoxCarCost": "6818",
          "Index": "0",
          "MealPeriodReporting": false,
          "IsItemLockout": false,
          "BaseCalories": "0",
          "SeatNumber": "1",
          "TareWeight": "0",
          "QuantityFraction": "0",
          "IsVoided": false,
          "RevenueGroup": "2",
          "ItemCoverCount": "0",
          "IsPackagePmixFlag": false,
          "ProfitCenterDimId": "0",
          "KvStatus": "1",
          "ReplacedItemId": "0",
          "DiscountAmount": "0",
          "AddedTime": "2025-05-19 05:50:07",
          "IsConsumed": true,
          "DisplayRoundId": "0",
          "QCQuantityMultiplier": "1",
          "ConfigItemIndex": "0",
          "ChoiceGroupId": "0",
          "IsGiftItem": false,
          "QCPriceMultiplier": "1",
          "RoundId": "0",
          "IsMaxItemPrice": false,
          "OpenItemInitialPrice": "6818",
          "PackagePmixAmount": "0",
          "IsPriceOverriden": false,
          "FixedInclusiveTax": "0",
          "PreviousVoidReasonId": "0",
          "IsModifier": false,
          "ThresholdTaxId": "0",
          "ItemGroupId": "1",
          "CheckViewCost": "6818",
          "MenuItemGroupName": "Default Item Group",
          "Id": "1080183",
          "Taxes": {
            "ExclusiveCost": "681.8",
            "InclusiveCost": "0",
            "FixedInclusiveCost": "0",
            "FixedExclusiveCost": "0",
            "RemovedTaxPercent": "0",
            "Count": "2",
            "Details": [
              {
                "UpdatedTaxRate": "0",
                "Id": "1",
                "TaxDimId": "0",
                "IsTaxByPercent": true,
                "TaxValue": "0",
                "IsExclusive": true,
                "IsTaxRemoved": false,
                "CanRemoveAtTerminal": true,
                "CategoryId": "1",
                "IsEarnEligible": false,
                "IsRedeemEligible": true,
                "RoundingConfiguration": {
                  "RoundType": "3",
                  "RoundBasis": "1"
                },
                "InclusiveCost": "0",
                "ExclusiveCost": "0",
                "Amount": "0",
                "TaxCost": "0"
              },
              {
                "UpdatedTaxRate": "0",
                "Id": "2",
                "TaxDimId": "0",
                "IsTaxByPercent": true,
                "TaxValue": "10",
                "IsExclusive": true,
                "IsTaxRemoved": false,
                "CanRemoveAtTerminal": true,
                "CategoryId": "1",
                "IsEarnEligible": false,
                "IsRedeemEligible": true,
                "RoundingConfiguration": {
                  "RoundType": "3",
                  "RoundBasis": "1"
                },
                "InclusiveCost": "0",
                "ExclusiveCost": "681.8",
                "Amount": "681.8",
                "TaxCost": "681.8"
              }
            ]
          }
        }
      ]
    },
    {
      "IsPriceOverride": false,
      "IsRestricted": false,
      "FixedExclusiveTaxAmount": "0",
      "KitchenItemIndex": "3",
      "DiscountAmount": "0",
      "OrderItemType": "0",
      "MaxItemPrice": "0",
      "OpenItemInitialPrice": "6364",
      "IsVoided": false,
      "IsSoldByWeight": false,
      "ItemTaxAmount": "636.4",
      "IsTaxRemoved": false,
      "IsConsumed": true,
      "CourseId": "1",
      "Cost": "6364",
      "SeatNumber": "1",
      "IsMaxItemPrice": false,
      "InclusiveGratuityAmount": "0",
      "QuantityFraction": "0",
      "IsOpenPrice": false,
      "Name": "Galvanina Orange",
      "IsOpenNamePrompt": false,
      "RestrictedItemGrossCost": "0",
      "SplitAllItemsMethod": "0",
      "IsReturnItem": false,
      "ReplacedItemId": "0",
      "OverrideApprovedBy": {
        "EmpShiftId": "0",
        "EmployeeDimId": "0",
        "Percentage": "0"
      },
      "IsVoidable": true,
      "ItemCheckNumber": "0",
      "IsBarGunItem": false,
      "ObjectIndex": "3",
      "RestrictedItemCost": "0",
      "FixedInclusiveTaxAmount": "0",
      "PackageId": "0",
      "RevenueCost": "0",
      "ItemCoverCount": "0",
      "IsSaved": false,
      "Quantity": "1",
      "DisplayCost": "6364",
      "GrossCost": "6364",
      "GetModifierCost": "0",
      "TotalTaxAmount": "636.4",
      "Index": "3",
      "NonTaxableAmount": "0",
      "InclusiveServiceChargeAmount": "0",
      "IsManualPackage": false,
      "UnRestrictedItemCost": "6364",
      "ReplacedItemDimId": "0",
      "InclusiveTaxAmount": "0",
      "AllowPriceOveride": true,
      "OrderItems": [
        {
          "SelectionGroupId": "0",
          "CheckTypeDimId": "0",
          "VoidReasonId": "0",
          "ItemQuantity": "0",
          "Cost": "6364",
          "MenuItemQuantityCategoryDimID": "0",
          "MaxCalories": "0",
          "ItemCheckNumber": "15000018",
          "PrimaryDiscountId": "0",
          "NonTaxableAmount": "0",
          "ProfitCenter": "18",
          "QuantityCategoryId": "0",
          "InclusiveGratuityAmount": "0",
          "Weight": "0",
          "ChoiceGroupFlag": false,
          "IsInclusiveGratuityModeEnabled": true,
          "UIIndex": "0",
          "ChildItemIndex": "0",
          "DisplayCost": "6364",
          "AddedBy": {
            "Id": "1",
            "EmpShiftId": "0",
            "EmployeeDimId": "0",
            "EmpJobCode": "8",
            "Name": "Supervisor",
            "Percentage": "0"
          },
          "IsRestricted": false,
          "IsPrintOnCheck": true,
          "Sequence": "0",
          "FixedExclusiveTax": "0",
          "CheckType": "18",
          "PickupInfo": {
            "IsLaterPickup": false
          },
          "AuxSplitFlag": false,
          "IsQCAddedModifier": false,
          "ModifierDimId": "0",
          "RevenueCost": "0",
          "MealCount": "0",
          "IsAppendModifier": false,
          "DisplayName": "18 Galvanina Orange",
          "ModifierIndex": "0",
          "IsManualWeight": false,
          "KpStatus": "1",
          "ScaleFactor": "1",
          "ItemSplitQuantityValue": "0",
          "ModifierCost": "0",
          "Name": "Galvanina Orange",
          "IsSaved": false,
          "IsAlcoholRestricted": false,
          "IsOpenItem": false,
          "MenuItemDimId": "0",
          "SKUCode": "8007885760939",
          "NumOfSplits": "0",
          "InclusiveTaxAmount": "0",
          "VoidReasonDimId": "0",
          "IsQCAddedItem": false,
          "OpenItem": {
            "Id": "0",
            "KitchenItemIndex": "0"
          },
          "ProductClassId": "35",
          "IsTaxInclusive": false,
          "CostBeforePackaging": "0",
          "IsDiscountable": true,
          "KitchenVideoCookTime": "0",
          "IsMealItem": false,
          "IUniqueSelGrpId": "0",
          "MaxItemPrice": "0",
          "IsSoldByWeight": false,
          "MealPeriod": "2",
          "IsTobaccoRestricted": false,
          "KitchenItemIndex": "3",
          "ItemVatTax": "0",
          "IsToDisplaySelGrpName": false,
          "TaxGroupId": "1",
          "IsSplitted": false,
          "KitchenVideoDepartmentId": "0",
          "ItemTaxAmount": "636.4",
          "ModifierProductMixDimId": "0",
          "TaxAmount": "636.4",
          "Quantity": "1",
          "ModifierProductMixRevenueCost": "0",
          "ReplacedItemDimId": "0",
          "IsStockItem": false,
          "MealPeriodDimId": "0",
          "IsReturnItem": false,
          "KitchenVideoCategoryId": "0",
          "InclusiveServiceChargeAmount": "0",
          "OriginProfitCenterDimId": "0",
          "ModifierProductMixId": "0",
          "ValidateThreshold": false,
          "UnitPrice": "6364",
          "RevenueCategory": {
            "InclusiveTaxAmount": "0",
            "SalesAmount": "0",
            "Id": "3",
            "IsRedeemEligible": true,
            "SalesAmountTaxInclusive": "0",
            "RevCatDimId": "0",
            "IsTenderRestricted": false,
            "IsEarnEligible": true,
            "NoTaxNetSales": "0",
            "GroupId": "4",
            "IRSFlag": true,
            "ExclusiveTaxAmount": "0",
            "TaxIclusiveItemDiscountAmount": "0",
            "DiscountAmount": "0"
          },
          "BoxCarCost": "6364",
          "Index": "0",
          "MealPeriodReporting": false,
          "IsItemLockout": false,
          "BaseCalories": "0",
          "SeatNumber": "1",
          "TareWeight": "0",
          "QuantityFraction": "0",
          "IsVoided": false,
          "RevenueGroup": "4",
          "ItemCoverCount": "0",
          "IsPackagePmixFlag": false,
          "ProfitCenterDimId": "0",
          "KvStatus": "1",
          "ReplacedItemId": "0",
          "DiscountAmount": "0",
          "AddedTime": "2025-05-19 05:50:25",
          "IsConsumed": true,
          "DisplayRoundId": "0",
          "QCQuantityMultiplier": "1",
          "ConfigItemIndex": "0",
          "ChoiceGroupId": "0",
          "IsGiftItem": false,
          "QCPriceMultiplier": "1",
          "RoundId": "0",
          "IsMaxItemPrice": false,
          "OpenItemInitialPrice": "6364",
          "PackagePmixAmount": "0",
          "IsPriceOverriden": false,
          "FixedInclusiveTax": "0",
          "PreviousVoidReasonId": "0",
          "IsModifier": false,
          "ThresholdTaxId": "0",
          "ItemGroupId": "1",
          "CheckViewCost": "6364",
          "MenuItemGroupName": "Default Item Group",
          "Id": "2040442",
          "Taxes": {
            "ExclusiveCost": "636.4",
            "InclusiveCost": "0",
            "FixedInclusiveCost": "0",
            "FixedExclusiveCost": "0",
            "RemovedTaxPercent": "0",
            "Count": "2",
            "Details": [
              {
                "UpdatedTaxRate": "0",
                "Id": "1",
                "TaxDimId": "0",
                "IsTaxByPercent": true,
                "TaxValue": "0",
                "IsExclusive": true,
                "IsTaxRemoved": false,
                "CanRemoveAtTerminal": true,
                "CategoryId": "1",
                "IsEarnEligible": false,
                "IsRedeemEligible": true,
                "RoundingConfiguration": {
                  "RoundType": "3",
                  "RoundBasis": "1"
                },
                "InclusiveCost": "0",
                "ExclusiveCost": "0",
                "Amount": "0",
                "TaxCost": "0"
              },
              {
                "UpdatedTaxRate": "0",
                "Id": "2",
                "TaxDimId": "0",
                "IsTaxByPercent": true,
                "TaxValue": "10",
                "IsExclusive": true,
                "IsTaxRemoved": false,
                "CanRemoveAtTerminal": true,
                "CategoryId": "1",
                "IsEarnEligible": false,
                "IsRedeemEligible": true,
                "RoundingConfiguration": {
                  "RoundType": "3",
                  "RoundBasis": "1"
                },
                "InclusiveCost": "0",
                "ExclusiveCost": "636.4",
                "Amount": "636.4",
                "TaxCost": "636.4"
              }
            ]
          }
        }
      ]
    },
    {
      "IsPriceOverride": false,
      "IsRestricted": false,
      "FixedExclusiveTaxAmount": "0",
      "KitchenItemIndex": "4",
      "DiscountAmount": "0",
      "OrderItemType": "0",
      "MaxItemPrice": "0",
      "OpenItemInitialPrice": "36363",
      "IsVoided": false,
      "IsSoldByWeight": false,
      "ItemTaxAmount": "3636.3",
      "IsTaxRemoved": false,
      "IsConsumed": true,
      "CourseId": "1",
      "Cost": "36363",
      "SeatNumber": "1",
      "IsMaxItemPrice": false,
      "InclusiveGratuityAmount": "0",
      "QuantityFraction": "0",
      "IsOpenPrice": false,
      "Name": "Lord bergamot",
      "IsOpenNamePrompt": false,
      "RestrictedItemGrossCost": "0",
      "SplitAllItemsMethod": "0",
      "IsReturnItem": false,
      "ReplacedItemId": "0",
      "OverrideApprovedBy": {
        "EmpShiftId": "0",
        "EmployeeDimId": "0",
        "Percentage": "0"
      },
      "IsVoidable": true,
      "ItemCheckNumber": "0",
      "IsBarGunItem": false,
      "ObjectIndex": "4",
      "RestrictedItemCost": "0",
      "FixedInclusiveTaxAmount": "0",
      "PackageId": "0",
      "RevenueCost": "0",
      "ItemCoverCount": "0",
      "IsSaved": false,
      "Quantity": "1",
      "DisplayCost": "36363",
      "GrossCost": "36363",
      "GetModifierCost": "0",
      "TotalTaxAmount": "3636.3",
      "Index": "4",
      "NonTaxableAmount": "0",
      "InclusiveServiceChargeAmount": "0",
      "IsManualPackage": false,
      "UnRestrictedItemCost": "36363",
      "ReplacedItemDimId": "0",
      "InclusiveTaxAmount": "0",
      "AllowPriceOveride": true,
      "OrderItems": [
        {
          "SelectionGroupId": "0",
          "CheckTypeDimId": "0",
          "VoidReasonId": "0",
          "ItemQuantity": "0",
          "Cost": "36363",
          "MenuItemQuantityCategoryDimID": "0",
          "MaxCalories": "0",
          "ItemCheckNumber": "15000018",
          "PrimaryDiscountId": "0",
          "NonTaxableAmount": "0",
          "ProfitCenter": "18",
          "QuantityCategoryId": "0",
          "InclusiveGratuityAmount": "0",
          "Weight": "0",
          "ChoiceGroupFlag": false,
          "IsInclusiveGratuityModeEnabled": true,
          "UIIndex": "0",
          "ChildItemIndex": "0",
          "DisplayCost": "36363",
          "AddedBy": {
            "Id": "1",
            "EmpShiftId": "0",
            "EmployeeDimId": "0",
            "EmpJobCode": "8",
            "Name": "Supervisor",
            "Percentage": "0"
          },
          "IsRestricted": false,
          "IsPrintOnCheck": true,
          "Sequence": "0",
          "FixedExclusiveTax": "0",
          "CheckType": "18",
          "PickupInfo": {
            "IsLaterPickup": false
          },
          "AuxSplitFlag": false,
          "IsQCAddedModifier": false,
          "ModifierDimId": "0",
          "RevenueCost": "0",
          "MealCount": "0",
          "IsAppendModifier": false,
          "DisplayName": "18 Lord bergamot",
          "ModifierIndex": "0",
          "IsManualWeight": false,
          "KpStatus": "1",
          "ScaleFactor": "1",
          "ItemSplitQuantityValue": "0",
          "ModifierCost": "0",
          "Name": "Lord bergamot",
          "IsSaved": false,
          "IsAlcoholRestricted": false,
          "IsOpenItem": false,
          "MenuItemDimId": "0",
          "SKUCode": "RB27",
          "NumOfSplits": "0",
          "InclusiveTaxAmount": "0",
          "VoidReasonDimId": "0",
          "IsQCAddedItem": false,
          "OpenItem": {
            "Id": "0",
            "KitchenItemIndex": "0"
          },
          "ProductClassId": "7",
          "IsTaxInclusive": false,
          "CostBeforePackaging": "0",
          "IsDiscountable": true,
          "KitchenVideoCookTime": "0",
          "IsMealItem": false,
          "IUniqueSelGrpId": "0",
          "MaxItemPrice": "0",
          "IsSoldByWeight": false,
          "MealPeriod": "2",
          "IsTobaccoRestricted": false,
          "KitchenItemIndex": "4",
          "ItemVatTax": "0",
          "IsToDisplaySelGrpName": false,
          "TaxGroupId": "1",
          "IsSplitted": false,
          "KitchenVideoDepartmentId": "0",
          "ItemTaxAmount": "3636.3",
          "ModifierProductMixDimId": "0",
          "TaxAmount": "3636.3",
          "Quantity": "1",
          "ModifierProductMixRevenueCost": "0",
          "ReplacedItemDimId": "0",
          "IsStockItem": false,
          "MealPeriodDimId": "0",
          "IsReturnItem": false,
          "KitchenVideoCategoryId": "0",
          "InclusiveServiceChargeAmount": "0",
          "OriginProfitCenterDimId": "0",
          "ModifierProductMixId": "0",
          "ValidateThreshold": false,
          "UnitPrice": "36363",
          "RevenueCategory": {
            "InclusiveTaxAmount": "0",
            "SalesAmount": "0",
            "Id": "1",
            "IsRedeemEligible": true,
            "SalesAmountTaxInclusive": "0",
            "RevCatDimId": "0",
            "IsTenderRestricted": false,
            "IsEarnEligible": true,
            "NoTaxNetSales": "0",
            "GroupId": "2",
            "IRSFlag": true,
            "ExclusiveTaxAmount": "0",
            "TaxIclusiveItemDiscountAmount": "0",
            "DiscountAmount": "0"
          },
          "BoxCarCost": "36363",
          "Index": "0",
          "MealPeriodReporting": false,
          "IsItemLockout": false,
          "BaseCalories": "0",
          "SeatNumber": "1",
          "TareWeight": "0",
          "QuantityFraction": "0",
          "IsVoided": false,
          "RevenueGroup": "2",
          "ItemCoverCount": "0",
          "IsPackagePmixFlag": false,
          "ProfitCenterDimId": "0",
          "KvStatus": "1",
          "ReplacedItemId": "0",
          "DiscountAmount": "0",
          "AddedTime": "2025-05-19 05:50:32",
          "IsConsumed": true,
          "DisplayRoundId": "0",
          "QCQuantityMultiplier": "1",
          "ConfigItemIndex": "0",
          "ChoiceGroupId": "0",
          "IsGiftItem": false,
          "QCPriceMultiplier": "1",
          "RoundId": "0",
          "IsMaxItemPrice": false,
          "OpenItemInitialPrice": "36363",
          "PackagePmixAmount": "0",
          "IsPriceOverriden": false,
          "FixedInclusiveTax": "0",
          "PreviousVoidReasonId": "0",
          "IsModifier": false,
          "ThresholdTaxId": "0",
          "ItemGroupId": "1",
          "CheckViewCost": "36363",
          "MenuItemGroupName": "Default Item Group",
          "Id": "1080174",
          "Taxes": {
            "ExclusiveCost": "3636.3",
            "InclusiveCost": "0",
            "FixedInclusiveCost": "0",
            "FixedExclusiveCost": "0",
            "RemovedTaxPercent": "0",
            "Count": "2",
            "Details": [
              {
                "UpdatedTaxRate": "0",
                "Id": "1",
                "TaxDimId": "0",
                "IsTaxByPercent": true,
                "TaxValue": "0",
                "IsExclusive": true,
                "IsTaxRemoved": false,
                "CanRemoveAtTerminal": true,
                "CategoryId": "1",
                "IsEarnEligible": false,
                "IsRedeemEligible": true,
                "RoundingConfiguration": {
                  "RoundType": "3",
                  "RoundBasis": "1"
                },
                "InclusiveCost": "0",
                "ExclusiveCost": "0",
                "Amount": "0",
                "TaxCost": "0"
              },
              {
                "UpdatedTaxRate": "0",
                "Id": "2",
                "TaxDimId": "0",
                "IsTaxByPercent": true,
                "TaxValue": "10",
                "IsExclusive": true,
                "IsTaxRemoved": false,
                "CanRemoveAtTerminal": true,
                "CategoryId": "1",
                "IsEarnEligible": false,
                "IsRedeemEligible": true,
                "RoundingConfiguration": {
                  "RoundType": "3",
                  "RoundBasis": "1"
                },
                "InclusiveCost": "0",
                "ExclusiveCost": "3636.3",
                "Amount": "3636.3",
                "TaxCost": "3636.3"
              }
            ]
          }
        }
      ]
    },
    {
      "IsPriceOverride": false,
      "IsRestricted": false,
      "FixedExclusiveTaxAmount": "0",
      "KitchenItemIndex": "5",
      "DiscountAmount": "0",
      "OrderItemType": "0",
      "MaxItemPrice": "0",
      "OpenItemInitialPrice": "7272",
      "IsVoided": false,
      "IsSoldByWeight": false,
      "ItemTaxAmount": "727.2",
      "IsTaxRemoved": false,
      "IsConsumed": true,
      "CourseId": "1",
      "Cost": "7272",
      "SeatNumber": "1",
      "IsMaxItemPrice": false,
      "InclusiveGratuityAmount": "0",
      "QuantityFraction": "0",
      "IsOpenPrice": false,
      "Name": "Chorizoe 200g",
      "IsOpenNamePrompt": false,
      "RestrictedItemGrossCost": "0",
      "SplitAllItemsMethod": "0",
      "IsReturnItem": false,
      "ReplacedItemId": "0",
      "OverrideApprovedBy": {
        "EmpShiftId": "0",
        "EmployeeDimId": "0",
        "Percentage": "0"
      },
      "IsVoidable": true,
      "ItemCheckNumber": "0",
      "IsBarGunItem": false,
      "ObjectIndex": "5",
      "RestrictedItemCost": "0",
      "FixedInclusiveTaxAmount": "0",
      "PackageId": "0",
      "RevenueCost": "0",
      "ItemCoverCount": "0",
      "IsSaved": false,
      "Quantity": "1",
      "DisplayCost": "7272",
      "GrossCost": "7272",
      "GetModifierCost": "0",
      "TotalTaxAmount": "727.2",
      "Index": "5",
      "NonTaxableAmount": "0",
      "InclusiveServiceChargeAmount": "0",
      "IsManualPackage": false,
      "UnRestrictedItemCost": "7272",
      "ReplacedItemDimId": "0",
      "InclusiveTaxAmount": "0",
      "AllowPriceOveride": true,
      "OrderItems": [
        {
          "SelectionGroupId": "0",
          "CheckTypeDimId": "0",
          "VoidReasonId": "0",
          "ItemQuantity": "0",
          "Cost": "7272",
          "MenuItemQuantityCategoryDimID": "0",
          "MaxCalories": "0",
          "ItemCheckNumber": "15000018",
          "PrimaryDiscountId": "0",
          "NonTaxableAmount": "0",
          "ProfitCenter": "18",
          "QuantityCategoryId": "0",
          "InclusiveGratuityAmount": "0",
          "Weight": "0",
          "ChoiceGroupFlag": false,
          "IsInclusiveGratuityModeEnabled": true,
          "UIIndex": "0",
          "ChildItemIndex": "0",
          "DisplayCost": "7272",
          "AddedBy": {
            "Id": "1",
            "EmpShiftId": "0",
            "EmployeeDimId": "0",
            "EmpJobCode": "8",
            "Name": "Supervisor",
            "Percentage": "0"
          },
          "IsRestricted": false,
          "IsPrintOnCheck": true,
          "Sequence": "0",
          "FixedExclusiveTax": "0",
          "CheckType": "18",
          "PickupInfo": {
            "IsLaterPickup": false
          },
          "AuxSplitFlag": false,
          "IsQCAddedModifier": false,
          "ModifierDimId": "0",
          "RevenueCost": "0",
          "MealCount": "0",
          "IsAppendModifier": false,
          "DisplayName": "18 Chorizoe 200g",
          "ModifierIndex": "0",
          "IsManualWeight": false,
          "KpStatus": "1",
          "ScaleFactor": "1",
          "ItemSplitQuantityValue": "0",
          "ModifierCost": "0",
          "Name": "Chorizoe 200g",
          "IsSaved": false,
          "IsAlcoholRestricted": false,
          "IsOpenItem": false,
          "MenuItemDimId": "0",
          "SKUCode": "R909",
          "NumOfSplits": "0",
          "InclusiveTaxAmount": "0",
          "VoidReasonDimId": "0",
          "IsQCAddedItem": false,
          "OpenItem": {
            "Id": "0",
            "KitchenItemIndex": "0"
          },
          "ProductClassId": "3",
          "IsTaxInclusive": false,
          "CostBeforePackaging": "0",
          "IsDiscountable": true,
          "KitchenVideoCookTime": "0",
          "IsMealItem": false,
          "IUniqueSelGrpId": "0",
          "MaxItemPrice": "0",
          "IsSoldByWeight": false,
          "MealPeriod": "2",
          "IsTobaccoRestricted": false,
          "KitchenItemIndex": "5",
          "ItemVatTax": "0",
          "IsToDisplaySelGrpName": false,
          "TaxGroupId": "1",
          "IsSplitted": false,
          "KitchenVideoDepartmentId": "0",
          "ItemTaxAmount": "727.2",
          "ModifierProductMixDimId": "0",
          "TaxAmount": "727.2",
          "Quantity": "1",
          "ModifierProductMixRevenueCost": "0",
          "ReplacedItemDimId": "0",
          "IsStockItem": false,
          "MealPeriodDimId": "0",
          "IsReturnItem": false,
          "KitchenVideoCategoryId": "0",
          "InclusiveServiceChargeAmount": "0",
          "OriginProfitCenterDimId": "0",
          "ModifierProductMixId": "0",
          "ValidateThreshold": false,
          "UnitPrice": "7272",
          "RevenueCategory": {
            "InclusiveTaxAmount": "0",
            "SalesAmount": "0",
            "Id": "1",
            "IsRedeemEligible": true,
            "SalesAmountTaxInclusive": "0",
            "RevCatDimId": "0",
            "IsTenderRestricted": false,
            "IsEarnEligible": true,
            "NoTaxNetSales": "0",
            "GroupId": "2",
            "IRSFlag": true,
            "ExclusiveTaxAmount": "0",
            "TaxIclusiveItemDiscountAmount": "0",
            "DiscountAmount": "0"
          },
          "BoxCarCost": "7272",
          "Index": "0",
          "MealPeriodReporting": false,
          "IsItemLockout": false,
          "BaseCalories": "0",
          "SeatNumber": "1",
          "TareWeight": "0",
          "QuantityFraction": "0",
          "IsVoided": false,
          "RevenueGroup": "2",
          "ItemCoverCount": "0",
          "IsPackagePmixFlag": false,
          "ProfitCenterDimId": "0",
          "KvStatus": "1",
          "ReplacedItemId": "0",
          "DiscountAmount": "0",
          "AddedTime": "2025-05-19 05:50:38",
          "IsConsumed": true,
          "DisplayRoundId": "0",
          "QCQuantityMultiplier": "1",
          "ConfigItemIndex": "0",
          "ChoiceGroupId": "0",
          "IsGiftItem": false,
          "QCPriceMultiplier": "1",
          "RoundId": "0",
          "IsMaxItemPrice": false,
          "OpenItemInitialPrice": "7272",
          "PackagePmixAmount": "0",
          "IsPriceOverriden": false,
          "FixedInclusiveTax": "0",
          "PreviousVoidReasonId": "0",
          "IsModifier": false,
          "ThresholdTaxId": "0",
          "ItemGroupId": "1",
          "CheckViewCost": "7272",
          "MenuItemGroupName": "Default Item Group",
          "Id": "1080148",
          "Taxes": {
            "ExclusiveCost": "727.2",
            "InclusiveCost": "0",
            "FixedInclusiveCost": "0",
            "FixedExclusiveCost": "0",
            "RemovedTaxPercent": "0",
            "Count": "2",
            "Details": [
              {
                "UpdatedTaxRate": "0",
                "Id": "1",
                "TaxDimId": "0",
                "IsTaxByPercent": true,
                "TaxValue": "0",
                "IsExclusive": true,
                "IsTaxRemoved": false,
                "CanRemoveAtTerminal": true,
                "CategoryId": "1",
                "IsEarnEligible": false,
                "IsRedeemEligible": true,
                "RoundingConfiguration": {
                  "RoundType": "3",
                  "RoundBasis": "1"
                },
                "InclusiveCost": "0",
                "ExclusiveCost": "0",
                "Amount": "0",
                "TaxCost": "0"
              },
              {
                "UpdatedTaxRate": "0",
                "Id": "2",
                "TaxDimId": "0",
                "IsTaxByPercent": true,
                "TaxValue": "10",
                "IsExclusive": true,
                "IsTaxRemoved": false,
                "CanRemoveAtTerminal": true,
                "CategoryId": "1",
                "IsEarnEligible": false,
                "IsRedeemEligible": true,
                "RoundingConfiguration": {
                  "RoundType": "3",
                  "RoundBasis": "1"
                },
                "InclusiveCost": "0",
                "ExclusiveCost": "727.2",
                "Amount": "727.2",
                "TaxCost": "727.2"
              }
            ]
          }
        }
      ]
    }
  ],
  "AddOnSummary": [],
  "GroupedAddOnSummary": [],
  "Tenders": [
    {
      "IsSplitTaxRemoved": false,
      "PmsPostSystem2": true,
      "amt_auto_adjusted": false,
      "TenderIndex": "0",
      "ReceiptsToPrint": "1",
      "PmsPostSystem8": false,
      "IsCreditTender": false,
      "AuthFlags": "0",
      "IsIRSAllocable": true,
      "IsPinPrompt": false,
      "SplitCheckId": "0",
      "CardCode": "",
      "AmountMaxAuth": "0",
      "VoidFlag": false,
      "CashTenderRoundAmount": "0",
      "WalletType": "None",
      "AccountType": "0",
      "CurrencyDecimalPrecision": "0",
      "IsRestricted": false,
      "PmsPostSystem4": false,
      "IsPmsAuth": false,
      "IsExternalTender": false,
      "ChangeId": "0",
      "IsOrderReceipt": false,
      "IsCompTender": false,
      "AdditionalCharge": "0",
      "IsCruisetender": false,
      "IsTenderReducesDiscount": false,
      "IsHostCapture": false,
      "PmsPostSystem6": false,
      "TenderClassId": "0",
      "IsExclusive": false,
      "BalanceAmount": "0",
      "IsSendRequestToPmsHost": false,
      "CardSource": "1",
      "PayIndex": "0",
      "TenderQty": "0",
      "IsTaxInvoice": false,
      "IsPost": false,
      "IsTipAvailableInAuthorization": false,
      "IsPatAcknowledge": false,
      "IsSaved": false,
      "IsDeposit": false,
      "TenderAdditionalInfo": {
        "FolioNumber": ""
      },
      "TenderGuid": "d239522f-20f3-43a5-ba45-3e0e224db371",
      "CurrencyExchangeScale": "0",
      "ExtraInfoIndex": "0",
      "DiscountId": "0",
      "IsAccountsReceivable": false,
      "TenderName": "***CASH",
      "pms_fidelio_flag": false,
      "AssociatedTenderGuid": "00000000-0000-0000-0000-000000000000",
      "hostCapture_flag": false,
      "AuthOnlyFlag": false,
      "Type": "0",
      "IsPatAuth": false,
      "EMVMobileFlag": false,
      "PmsPostSystem5": false,
      "SourceProperty": "",
      "AdapterConfigurationId": "0",
      "TaxAmount": "1818.27",
      "CurrencyExchangeFactor": "0",
      "ChangeAmount": "0",
      "tenderInfo": {
        "EntryMode": "0",
        "IsRestricted": false,
        "VerificationMode": "2",
        "EncryptionMode": "0",
        "isEngageOfflineTender": false,
        "PMSSubType": "4",
        "AuthTime": "0",
        "TenderId": "47",
        "IsSecondarySystem": false,
        "IsAutoRemoveTax": false,
        "TenderDimId": "0",
        "IsFallBack": false,
        "EncryptionSeed": "0",
        "RFIDFlag": false,
        "TotalAmount": "0",
        "PMSType": "0",
        "IsLookupOnly": false
      },
      "PmsPostSystem7": false,
      "CurrencyAmount": "20000",
      "IsRedeemEligible": false,
      "AllowDuplicateReceipts": false,
      "PmsPostSystem1": false,
      "TenderDimId": "0",
      "Index": "0",
      "isAuth": false,
      "SmSettleFlag": "0",
      "BreakageAmount": "0",
      "PmsPostSystem3": false,
      "TipAmount": "0",
      "VerificationCodeId": "0",
      "RealTimePostSiteId": "0",
      "DestinationProperty": "",
      "PmsSiteId": "1",
      "IsPostToPms": true,
      "AllocatedRevenueAmount": "0",
      "AdaptorName": "Cash",
      "AdaptorType": "2",
      "Amount": "20000",
      "IsAutoRemoveTax": false,
      "IsAuthBenefit": false,
      "VerifyStatus": "0",
      "ObjectIndex": "6",
      "amt_tpg_auth": "0",
      "IsEarnEligible": true,
      "Id": "47"
    },
    {
      "IsSplitTaxRemoved": false,
      "PmsPostSystem2": false,
      "amt_auto_adjusted": false,
      "TenderIndex": "1",
      "ReceiptsToPrint": "1",
      "PmsPostSystem8": false,
      "IsCreditTender": false,
      "AuthFlags": "0",
      "IsIRSAllocable": true,
      "IsPinPrompt": false,
      "SplitCheckId": "0",
      "CardCode": "",
      "AmountMaxAuth": "0",
      "VoidFlag": false,
      "CashTenderRoundAmount": "0",
      "WalletType": "None",
      "AccountType": "0",
      "CurrencyDecimalPrecision": "0",
      "IsRestricted": false,
      "PmsPostSystem4": false,
      "IsPmsAuth": false,
      "IsExternalTender": false,
      "ChangeId": "0",
      "IsOrderReceipt": false,
      "IsCompTender": false,
      "AdditionalCharge": "0",
      "IsCruisetender": false,
      "IsTenderReducesDiscount": false,
      "IsHostCapture": false,
      "PmsPostSystem6": false,
      "TenderClassId": "0",
      "IsExclusive": false,
      "BalanceAmount": "0",
      "IsSendRequestToPmsHost": false,
      "CardSource": "1",
      "PayIndex": "0",
      "TenderQty": "0",
      "IsTaxInvoice": false,
      "IsPost": false,
      "IsTipAvailableInAuthorization": false,
      "IsPatAcknowledge": false,
      "IsSaved": false,
      "IsDeposit": false,
      "TenderAdditionalInfo": {
        "FolioNumber": ""
      },
      "TenderGuid": "595d5df1-b414-4996-bae3-bbed174e2833",
      "CurrencyExchangeScale": "0",
      "ExtraInfoIndex": "0",
      "DiscountId": "0",
      "IsAccountsReceivable": false,
      "TenderName": "*OFF-CREDIT CARD",
      "pms_fidelio_flag": false,
      "AssociatedTenderGuid": "00000000-0000-0000-0000-000000000000",
      "hostCapture_flag": false,
      "AuthOnlyFlag": false,
      "Type": "0",
      "IsPatAuth": false,
      "EMVMobileFlag": false,
      "PmsPostSystem5": false,
      "SourceProperty": "",
      "AdapterConfigurationId": "0",
      "TaxAmount": "3863.73",
      "CurrencyExchangeFactor": "0",
      "ChangeAmount": "0",
      "tenderInfo": {
        "EntryMode": "0",
        "IsRestricted": false,
        "VerificationMode": "2",
        "EncryptionMode": "0",
        "isEngageOfflineTender": false,
        "PMSSubType": "4",
        "AuthTime": "0",
        "TenderId": "53",
        "IsSecondarySystem": false,
        "IsAutoRemoveTax": false,
        "TenderDimId": "0",
        "IsFallBack": false,
        "EncryptionSeed": "0",
        "RFIDFlag": false,
        "TotalAmount": "0",
        "PMSType": "0",
        "IsLookupOnly": false
      },
      "PmsPostSystem7": false,
      "CurrencyAmount": "42499",
      "IsRedeemEligible": false,
      "AllowDuplicateReceipts": false,
      "PmsPostSystem1": false,
      "TenderDimId": "0",
      "Index": "1",
      "isAuth": false,
      "SmSettleFlag": "0",
      "BreakageAmount": "0",
      "PmsPostSystem3": false,
      "TipAmount": "0",
      "VerificationCodeId": "0",
      "RealTimePostSiteId": "0",
      "DestinationProperty": "",
      "PmsSiteId": "1",
      "IsPostToPms": false,
      "AllocatedRevenueAmount": "0",
      "AdaptorName": "Cash",
      "AdaptorType": "2",
      "Amount": "42499",
      "IsAutoRemoveTax": false,
      "IsAuthBenefit": false,
      "VerifyStatus": "0",
      "ObjectIndex": "7",
      "amt_tpg_auth": "0",
      "IsEarnEligible": true,
      "Id": "53"
    }
  ],
  "TaxSummary": [
    {
      "InclusiveTaxAmount": "0",
      "SalesAmount": "56817",
      "Id": "1",
      "IsRedeemEligible": true,
      "RoundingConfiguration": {
        "RoundType": "3",
        "RoundBasis": "1"
      },
      "CompoundAmount": "0",
      "ReCalculatedExclusiveTax": "0",
      "RevenueCategoryId": "1",
      "SalesAmountTaxInclusive": "0",
      "CategoryId": "1",
      "ServiceCharge_Or_Grat_Id": "0",
      "IsEarnEligible": false,
      "GroupId": "1",
      "SalesBasis": "56817",
      "GratuityBasis": "0",
      "ExclusiveTaxAmount": "0",
      "ServiceAmount": "0",
      "TaxDimId": "0",
      "GratuityAmount": "0",
      "AddOnTax": "0",
      "AddOnType": "0",
      "DiscountAmount": "0"
    },
    {
      "InclusiveTaxAmount": "0",
      "SalesAmount": "56817",
      "Id": "2",
      "IsRedeemEligible": true,
      "RoundingConfiguration": {
        "RoundType": "3",
        "RoundBasis": "1"
      },
      "CompoundAmount": "0",
      "ReCalculatedExclusiveTax": "0",
      "RevenueCategoryId": "1",
      "SalesAmountTaxInclusive": "0",
      "CategoryId": "1",
      "ServiceCharge_Or_Grat_Id": "0",
      "IsEarnEligible": false,
      "GroupId": "1",
      "SalesBasis": "56817",
      "GratuityBasis": "0",
      "ExclusiveTaxAmount": "5682",
      "ServiceAmount": "0",
      "TaxDimId": "0",
      "GratuityAmount": "0",
      "AddOnTax": "5682",
      "AddOnType": "0",
      "DiscountAmount": "0"
    }
  ],
  "Revenuecategories": [
    {
      "InclusiveTaxAmount": "0",
      "SalesAmount": "0",
      "Id": "5",
      "SalesAmountTaxInclusive": "0",
      "RevCatDimId": "0",
      "IsTenderRestricted": false,
      "NoTaxNetSales": "0",
      "GroupId": "3",
      "IRSFlag": true,
      "ExclusiveTaxAmount": "0",
      "TaxIclusiveItemDiscountAmount": "0",
      "NoPercentTaxNetSales": "0",
      "DiscountAmount": "0"
    },
    {
      "InclusiveTaxAmount": "0",
      "SalesAmount": "50453",
      "Id": "1",
      "SalesAmountTaxInclusive": "0",
      "RevCatDimId": "0",
      "IsTenderRestricted": false,
      "NoTaxNetSales": "0",
      "GroupId": "2",
      "IRSFlag": true,
      "ExclusiveTaxAmount": "5045",
      "TaxIclusiveItemDiscountAmount": "0",
      "NoPercentTaxNetSales": "0",
      "DiscountAmount": "0"
    },
    {
      "InclusiveTaxAmount": "0",
      "SalesAmount": "6364",
      "Id": "3",
      "SalesAmountTaxInclusive": "0",
      "RevCatDimId": "0",
      "IsTenderRestricted": false,
      "NoTaxNetSales": "0",
      "GroupId": "4",
      "IRSFlag": true,
      "ExclusiveTaxAmount": "636",
      "TaxIclusiveItemDiscountAmount": "0",
      "NoPercentTaxNetSales": "0",
      "DiscountAmount": "0"
    }
  ]
}

/*
         Grand Deli       
=================================
Date: 2025. 05. 19. 14
Check:[15000018]    Cover: 1  
Cashier: Supervisor Table: D20  
=================================

          Grand DeliCheck
==================================
******* After Order Header *******
       1 Mini gouda 20       6,818
       1 Galvanina Orange    6,364
       1 Lord bergamot      36,363
       1 Chorizoe 200g       7,272
******** After Menu Items ********
==================================
SUBTOTAL           56,817
Service Charge          0
VAT                 5,682
=================================
Amount Due         62,499
=================================
                            

******** After Sub Total *********
***CASH                     20,000
*OFF-CREDIT CARD            42,499
********* After Tenders **********
           GRAND TOTAL      62,499
=================================
T150 C1      2025. 05. 19. 14
=================================
Room & Member No. : _____________

Guest Name : ____________________

Signature : _____________________


**** Your Custom Receipt Text ****
 English Name: Michele Teves
 Korean Name: 미쉘 테베스
**********************************
*/
